os: osx
osx_image: xcode10.2
branches:
  only:
    - master
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
script:
  - set -o pipefail
  - swift --version
  - swift build
  - swift test
